### ISSUE TITLE
DOI to data not working

### ISSUE THREAD

**Issue by egonw** [chanzuckerberg/software-mentions#1]
The DOI link gives a "DOI Not Found":

![image](https://user-images.githubusercontent.com/26721/189472901-3357707d-b32c-4a50-aa47-6cbe5943fd1b.png)

**Comment by borisveytsman** [comment]
Thanks for the interest in the dataset.  The dataset is in curation, and will be released to the public very soon.

**Comment by borisveytsman** [comment]
It is now public!
